config/routes.rb
Rails.application.routes.draw do
  
  root "reminders#index"
  devise_for :users
  resources :reminders

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
# == Schema Information
#
# Table name: reminders
#
#  id            :bigint(8)        not null, primary key
#  title         :string
#  description   :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint(8)
#  day_direction :string
#  day_number    :integer
#  timezone      :string
#  send_time     :time
#

class Reminder < ApplicationRecord
  include ActiveSupport

  attr_accessor :hour, :minute

  validates :title, presence: true
  validates :description, presence: true
  validates :day_direction, presence: true
  validates :day_number, presence: true, 
                         numericality: { 
                           greater_than_or_equal_to: 1, 
                           less_than_or_equal_to: 31 
                         }
  validates :timezone, presence: true
  validates :send_time, presence: true
  validates_inclusion_of :day_direction, in: :allowed_directions
  validates_inclusion_of :timezone, in: :allowed_timezones

  belongs_to :user

  after_create :send_confirmation_email
  after_create :schedule_reminders

  module DayDirections
    FROM_BEGINNING = "from_beginning"
    FROM_END = "from_end"
  end

  def allowed_directions
    DayDirections.constants(false).map{ |c| DayDirections.const_get(c) }
  end

  def allowed_timezones
    timezones = TimeZone.all.map(&:name)
    return timezones
  end

  def day_direction_display
    if day_direction == DayDirections::FROM_END
      return "end"
    else
      return "beginning"
    end
  end

  def timezone_display
    Time.now.in_time_zone(ActiveSupport::TimeZone[timezone]).strftime('%Z')
  end

  def calculate_send_date_for(year, month)
    # This method expects arguments in integers (e.g. (2012, 8))

    scheduled_date = send_time.change(year: year, month: month, day: relative_sending_day(year, month))
  end

  def upcoming_send_dates(months)
    # This method expects an integer representing the number of
    # upcoming months to calculate.

    today = Time.now
    date_collection = []
    this_month = calculate_send_date_for(today.year, today.month)

    if this_month.past?
      (1..months).each do |n|
        date_collection << this_month.advance(months: n)
      end
    else
      (0..months-1).each do |n|
        date_collection << this_month.advance(months: n)
      end
    end

    return date_collection
  end

  def next_occurrence
    upcoming_send_dates(1).first
  end

  def send_confirmation_email
    ReminderMailer.confirmation_email(self).deliver_now
  end

  def schedule_reminders
    ReminderWorker.perform_at(next_occurrence, id)
  end


  private

  def absolute_sending_day
    # This method calculates the day of the month on which 
    # a reminder should ideally be sent if the day is available
    # (i.e. assuming the month has 31 days).

    calculated_day = day_number

    if day_direction == DayDirections::FROM_END
      calculated_day = 31 - (day_number - 1)
    end

    return calculated_day
  end

  def relative_sending_day(year, month)
    # This method expects arguments in integers (e.g. (2012, 8))
    # and calculates the day on which a reminder should be sent
    # within a specific month, accounting for variations in the number
    # of days in each month.

    calculated_day = absolute_sending_day
    target_month = Time.new(year, month, 1, 0,0,0)

    if absolute_sending_day > target_month.end_of_month.day
      calculated_day = target_month.end_of_month.day
    end

    return calculated_day
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reminders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!
  def index
    @reminders = current_user.reminders.all
  end

  def new
  end

  def create
    reminder = Reminder.new(user: current_user, 
                            title: reminder_params[:title], 
                            description: reminder_params[:description],
                            day_direction: reminder_params[:day_direction],
                            day_number: reminder_params[:day_number],
                            timezone: reminder_params[:timezone],
                            send_time: parsed_send_time)
    if reminder.save!
      flash[:notice] = "New reminder created!"
      redirect_to reminders_path
    else
      flash[:alert] = "Post cannot be saved. Please make sure you've included all necessary information."
    end
  end

  def show
    @reminder = Reminder.where(id: params[:id]).first
  end

  def destroy
    @reminder = Reminder.where(id: params[:id]).first
    @reminder.destroy

    flash[:notice] = "Reminder deleted"
    redirect_to reminders_path
  end


  private

  def reminder_params
    params.require(:reminder).permit(:title, 
                                     :description, 
                                     :day_direction, 
                                     :day_number, 
                                     :timezone, 
                                     :hour, 
                                     :minute)
  end

  def parsed_send_time
    assembled_time = reminder_params[:hour].to_s + ":" + reminder_params[:minute].to_s
    parsed_time = ActiveSupport::TimeZone.new(reminder_params[:timezone])
                                              .parse(assembled_time)
    return parsed_time
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="header">
    <div class="wrapper">
        <div class="grid">
            <div class="grid-col grid-col_6of12">
                <%= link_to root_url do %>
                    <h1 class="hdg hdg_1 hdg_white">Reminder Scheduler</h1>
                <% end %>
            </div>
            <div class="grid-col grid-col_6of12">
                <div class="text_right">
                    <% if user_signed_in? %>
                        <div class="mod">
                            <div>
                                <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
                            </div>
                            <div class="text_small">
                                Signed in as: <%= current_user.try(:email) %>
                            </div>
                        </div>
                    <% else %>
                        <%= link_to('Login', new_user_session_path)  %>
                        |
                        <%= link_to('Register', new_user_registration_path)  %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminderScheduler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="wrapper">

      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/reminders/index.html.erb
<h2 class="hdg hdg_2">Reminders Index</h2>

<div class="vr">
    <div class="text_right">
        <%= link_to 'Create New Reminder', new_reminder_path, class: "btn" %>
    </div>
</div>

<% if @reminders.any? %>
    <div class="vr">
        <table class="table">
            <tr>
                <th>Title</th>
                <th>Next Send Date</th> 
                <th>Actions</th>
            </tr>
            <% @reminders.each do |reminder| %>
                <tr>
                    <td><%= link_to reminder.title, reminder_path(reminder) %></td>
                    <td>TBD</td> 
                    <td>
                        <%= link_to 'Delete',  reminder,  method: :delete, data: { confirm: 'Are you sure you want to delete this remider permanently?' } %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
<% else %>
    <div>You have no reminders</div>
<% end %>

app/views/reminders/new.html.erb
<h2 class="hdg hdg_2">Create New Reminder</h2>

<div class="vr">
    <%= form_for(Reminder.new) do |f| %>
        <%= f.hidden_field :user_id, { :value => current_user.id } %>

        <div class="mod">
            <div>
                <h3 class="hdg hdg_3">Title</h3>
                <%= f.text_field :title, class: "form_field" %>
            </div>
            <div>
                <h3 class="hdg hdg_3">Description</h3>
                <%= f.text_area :description, class: "form_field" %>
            </div>

            <div>
                <h3 class="hdg hdg_3">Day of Month</h3>
                Send my reminder on the
                <select name="reminder[day_number]">
                    <% (1..31).each do |n| %>
                        <option value="<%= n %>"><%= n.ordinalize %></option>
                    <% end %>
                </select>
                day from the
                <select name="reminder[day_direction]">
                    <option value="from_beginning">beginning</option>
                    <option value="from_end">end</option>
                </select>
                of each month.<br /><br />

                <div class="text_small">(For days that do not exist in a given month, the reminder will be sent on the closest available day within the same month.)</div>
            </div>

            <div>
                <h3 class="hdg hdg_3">Time of Day</h3>
                Hour: <%= f.select :hour, (0..23) %> Minute: <%= f.select :minute, (0..59) %>
            </div>

            <div>
                <h3 class="hdg hdg_3">Time Zone</h3>
                <%#= f.select :timezone, "#{Reminder.new.allowed_timezones}" %>
                <select name="reminder[timezone]">
                    <% ActiveSupport::TimeZone.all.each do |zone| %>
                        <option value="<%= zone.name %>">
                            <%= zone.name %> (<%= zone.formatted_offset %>)
                        </option>
                    <% end %>
                </select>
            </div>
        </div>
        
        <div class="vr text_right">
            <div class="hlist">
                <div><%= f.submit "Create Reminder", class: "btn" %></div>
                <div><%= link_to "Return to Index", root_path, class: "btn" %></div>
            </div>
        </div>
    <% end %>
</div>

app/views/reminders/show.html.erb
<h2 class="hdg hdg_2">Reminder #<%= @reminder.id %></h2>

<div class="vr">
    <div class="mod">
        <div>
            <div class="hdg hdg_3">User Email</div>
            <div><%= @reminder.try(:user).try(:email) %></div>
        </div>
        <div>
            <div class="hdg hdg_3">Title</div>
            <div><%= @reminder.try(:title) %></div>
        </div>
        <div>
            <div class="hdg hdg_3">Description</div>
            <div><%= @reminder.try(:description) %></div>
        </div>
        <div>
            <div class="hdg hdg_3">Send Rhythm</div>
            <div>This reminder will be sent <span class="text_strong">monthly</span>, on the 
                <span class="text_strong"><%= @reminder.try(:day_number).try(:ordinalize) %></span> 
                day from the 
                <span class="text_strong"><%= @reminder.try(:day_direction_display) %></span>
                of the month, at 
                <span class="text_strong"><%= @reminder.try(:send_time).in_time_zone(@reminder.try(:timezone)).strftime("%H:%M") %> (<%= @reminder.try(:timezone_display) %>)</span>.
            </div>
        </div>
        <div>
            <div class="hdg hdg_3">Upcoming Send Dates</div>
            <table class="table">
                <tr>
                    <th>Year</th>
                    <th>Date</th>
                    <th>Time</th>
                </tr>
                <% @reminder.upcoming_send_dates(6).each do |date| %>
                    <tr>
                        <td>
                            <%= date.in_time_zone(@reminder.timezone).strftime("%Y") %>
                        </td>
                        <td>
                            <%= date.in_time_zone(@reminder.timezone).strftime("%B %d") %>
                        </td>
                        <td>
                            <%= date.in_time_zone(@reminder.timezone).strftime("%H:%M (%Z)") %>
                        </td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

<div class="vr text_right">
    <div class="hlist">
        <div>
            <%= link_to 'Delete Reminder',  @reminder,  method: :delete, data: { confirm: 'Are you sure you want to delete this remider permanently?' }, class: "btn" %>
        </div>
        <%= link_to "Return to Index", root_path, class: "btn" %>
    </div>
</div>